#! /bin/bash

HERE=`dirname "$0"`
docker build -t "podcast-stuff" .
docker run \
       --mount readonly,type=bind,source=$HERE/../podcast-stuff-secrets/internetarchive,target=/root/.config/internetarchive \
       --mount readonly,type=bind,source=$HERE/script,target=/root/src \
       --mount readonly,type=bind,source=$HOME/.ssh,target=/root/.ssh \
       -it \
       podcast-stuff \
       bash
